# xarm:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
L_joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint1
  pid: {p: 1200.0, i: 5.0, d: 10.0}
L_joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint2
  pid: {p: 1400.0, i: 5.0, d: 10.0}
L_joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint3
  pid: {p: 1200.0, i: 5.0, d: 5.0}
L_joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint4
  pid: {p: 850.0, i: 3.0, d: 5.0}
L_joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint5
  pid: {p: 500.0, i: 3.0, d: 1.0}
L_joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: L_joint6
  pid: {p: 500.0, i: 1.0, d: 1.0}


R_joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint1
  pid: {p: 1200.0, i: 5.0, d: 10.0}
R_joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint2
  pid: {p: 1400.0, i: 5.0, d: 10.0}
R_joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint3
  pid: {p: 1200.0, i: 5.0, d: 5.0}
R_joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint4
  pid: {p: 850.0, i: 3.0, d: 5.0}
R_joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint5
  pid: {p: 500.0, i: 3.0, d: 1.0}
R_joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: R_joint6
  pid: {p: 500.0, i: 1.0, d: 1.0}




