# xarm:
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
L_xarm5_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    L_joint1: {trajectory: 1, goal: 0.01}
    L_joint2: {trajectory: 1, goal: 0.01}
    L_joint3: {trajectory: 1, goal: 0.01}
    L_joint4: {trajectory: 1, goal: 0.01}
    L_joint5: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10

L_xarm5_traj_controller_velocity:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
  gains:
    L_joint1: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    L_joint2: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    L_joint3: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    L_joint4: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    L_joint5: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
  velocity_ff:
    L_joint1: 0.25
    L_joint2: 0.25
    L_joint3: 0.25
    L_joint4: 0.25
    L_joint5: 0.25
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    L_joint1: {trajectory: 1, goal: 0.01}
    L_joint2: {trajectory: 1, goal: 0.01}
    L_joint3: {trajectory: 1, goal: 0.01}
    L_joint4: {trajectory: 1, goal: 0.01}
    L_joint5: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10

R_xarm5_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    R_joint1: {trajectory: 1, goal: 0.01}
    R_joint2: {trajectory: 1, goal: 0.01}
    R_joint3: {trajectory: 1, goal: 0.01}
    R_joint4: {trajectory: 1, goal: 0.01}
    R_joint5: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10

R_xarm5_traj_controller_velocity:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
  gains:
    R_joint1: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    R_joint2: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    R_joint3: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    R_joint4: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    R_joint5: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
  velocity_ff:
    R_joint1: 0.25
    R_joint2: 0.25
    R_joint3: 0.25
    R_joint4: 0.25
    R_joint5: 0.25
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    R_joint1: {trajectory: 1, goal: 0.01}
    R_joint2: {trajectory: 1, goal: 0.01}
    R_joint3: {trajectory: 1, goal: 0.01}
    R_joint4: {trajectory: 1, goal: 0.01}
    R_joint5: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10

# No Pid gains specified error fix
# gazebo_ros_control:
#   pid_gains:
#     joint1: {p: 1200.0, i: 5.0, d: 10.0}
#     joint2: {p: 1400.0, i: 5.0, d: 10.0}
#     joint3: {p: 1200.0, i: 5.0, d: 5.0}
#     joint4: {p: 500.0, i: 3.0, d: 1.0}
#     joint5: {p: 500.0, i: 1.0, d: 1.0}

