controller_list:
  - name: fake_xarm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_robotiq_gripper_controller
    type: $(arg execution_type)
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: xarm6
    pose: home
  - group: robotiq_gripper
    pose: open