sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    max_update_rate: 0.5
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /camera/pointcloud
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
