sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/depth/image_rect_raw
    queue_size: 5
    near_clipping_plane_distance: 0.1
    far_clipping_plane_distance: 1.0
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.05
    max_update_rate: 0.5    # in Hz
    filtered_cloud_topic: filtered_cloud
